repositories:
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts

releases:
  - name: cloudnative-pg
    namespace: "{{ .Values | get \"namespace\" \"cnpg-database\" }}"
    chart: cnpg/cluster
    createNamespace: true
    wait: true
    values:
      - values.yaml