# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# and
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/auth/keycloak/scripts"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*" # ignore dependencies for demo script
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "weekly"