{
 "title": "AIStore",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "proxy",
    "label": "Proxy",
    "query": {
     "query": "{__name__=~\"ais_proxy_.*\"}"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "{__name__=~\"ais_target_.*\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance) "
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "node_count",
    "query": {
     "query": "query_result(count(kube_node_info))"
    }
   },
   {
    "name": "network_devices",
    "label": "Network Devices",
    "query": {
     "query": "label_values(node_network_info, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "AIStore Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Used",
   "type": "gauge",
   "description": "Percentage of AIStore storage used across the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})) / sum(node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Inodes Used",
   "type": "gauge",
   "description": "Percentage of inodes used across the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_files{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - sum(node_filesystem_files_free{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})) / sum(node_filesystem_files{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) * 100\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total AIstore errors / sec",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_n\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / Sec",
   "type": "stat",
   "description": "Total AIStore requests per second",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_.*_n\"}[5m]))",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Unavailable Proxies",
   "type": "gauge",
   "description": "Unavailable AIStore proxy replicas",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(kube_statefulset_status_replicas{statefulset=~\".*proxy$\", namespace=\"${namespace}\"}) - min(kube_statefulset_status_replicas_ready{statefulset=~\".*proxy$\", namespace=\"${namespace}\"})) / max(kube_statefulset_status_replicas{statefulset=~\".*proxy$\", namespace=\"${namespace}\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Targets",
   "type": "gauge",
   "description": "Unavailable AIStore target replicas",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(kube_statefulset_status_replicas{statefulset=~\".*target$\", namespace=\"${namespace}\"}) - min(kube_statefulset_status_replicas_ready{statefulset=~\".*target$\", namespace=\"${namespace}\"})) / max(kube_statefulset_status_replicas{statefulset=~\".*target$\", namespace=\"${namespace}\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Nodes",
   "type": "gauge",
   "description": "Unavailable cluster nodes",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{daemonset=\"kube-prometheus-stack-prometheus-node-exporter\"} / ${node_count}"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "stat",
   "description": "Total Raw Storage Capacity",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})\n"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Mean AIstore target request latency for operations.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"ais_target_${target}_.*_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_get_redir_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_put_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_put_redir_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_keepalive_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_list_ms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Total receive and transmit cluster network throughput",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total[5m])) + sum(rate(node_network_transmit_bytes_total[5m]))) * 8",
     "legendFormat": "Recieve {{device}}"
    }
   ]
  },
  {
   "title": "Proxy Count",
   "type": "stat",
   "description": "AIStore proxy replica count",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*proxy\", namespace=\"${namespace}\"}"
    }
   ]
  },
  {
   "title": "Target Count",
   "type": "stat",
   "description": "AIStore target replica count",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*target\", namespace=\"${namespace}\"}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "Count of physical machines in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  { "title": "Hardware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Mean busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"^$node$\",job=\"node-exporter\", mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"^${node}$\",job=\"node-exporter\"}[5m])))) * 100)\n"
    }
   ]
  },
  {
   "title": "Load (5m)",
   "type": "gauge",
   "description": "Mean 5m load average",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load5{instance=~\"^${node}$\",job=\"node-exporter\"}) / count(count(node_cpu_seconds_total{instance=~\"^${node}$\", job=\"node-exporter\"}) by (cpu, instance))) * 100"
    }
   ]
  },
  {
   "title": "Load (15m)",
   "type": "gauge",
   "description": "Mean 15m load average",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load15{instance=~\"^${node}$\",job=\"node-exporter\"}) / count(count(node_cpu_seconds_total{instance=~\"^${node}$\", job=\"node-exporter\"}) by (cpu, instance))) * 100\n"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Mean RAM usage",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{instance=~\"^${node}$\",job=\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\"}))"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "description": "Mean swap usage",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((node_memory_SwapTotal_bytes{instance=~\"^${node}$$\",job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~\"^${node}$\",job=\"node-exporter\"}) / (node_memory_SwapTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\"} )) * 100)"
    }
   ]
  },
  {
   "title": "Max Root FS",
   "type": "gauge",
   "description": "The top root filesystem usage across the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/\",fstype!=\"rootfs\"}))\n"
    }
   ]
  },
  {
   "title": "Core Count",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"^${node}$\",job=\"node-exporter\"}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"^${node}\",job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 } },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Storage Used vs Free",
   "type": "timeseries",
   "description": "Total cluster storage used and free",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"})",
     "legendFormat": "Free Storage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Storage Used: Top 5 Disks",
   "type": "timeseries",
   "description": "Top five storage-using disks and nodes, as % full",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, (100 - 100 * sum by (instance, device) (node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"}) / sum by (instance, device) (node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"})))\n",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "Inodes Used",
   "type": "timeseries",
   "description": "Used Inodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_files{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - sum(node_filesystem_files_free{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})) / sum(node_filesystem_files{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) * 100\n",
     "legendFormat": "Percent Inodes Used"
    }
   ]
  },
  {
   "title": "Inodes Used: Top 5 Disks",
   "type": "timeseries",
   "description": "Top 5 inode-using disks / nodes, as % full",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, ((node_filesystem_files{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - (node_filesystem_files_free{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})) / (node_filesystem_files{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) * 100)\n",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "AIStore Error Rates by Operation",
   "type": "timeseries",
   "description": "AIStore error rates, broken down by operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_n\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_get_n\"}[5m]))",
     "legendFormat": "Total errors / sec"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_delete_n\"}[5m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_post_n\"}[5m]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_put_n\"}[5m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_head_n\"}[5m]))",
     "legendFormat": "HEAD"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_list_n\"}[5m]))",
     "legendFormat": "list"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_range_n\"}[5m]))",
     "legendFormat": "range"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_dl_n\"}[5m]))",
     "legendFormat": "dl"
    }
   ]
  },
  {
   "title": "Disk Error Rates By Node",
   "type": "timeseries",
   "description": "Disk error rates, broken down by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_filesystem_device_error{mountpoint=~\"^/ais/.*$\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Request Rate by Operation",
   "type": "timeseries",
   "description": "Requests per second, broken down by AIStore operation",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_get_n\"}[5m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_put_n\"}[5m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_delete_n\"}[5m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_append_n\"}[5m]))",
     "legendFormat": "append"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_ren_n\"}[5m]))",
     "legendFormat": "rename"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_lst_n\"}[5m]))",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "Read, Write, Total Throughput",
   "type": "timeseries",
   "description": "Read, write, and total AIStore target throughput.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum({__name__=~\"ais_target_${target}_disk_.*_read_mbps\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_disk_.*_write_mbps\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_.*_mbps\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Network RX / TX",
   "type": "timeseries",
   "description": "Total receive and transmit cluster network throughput",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) * 8",
     "legendFormat": "Recieve {{device}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) * 8",
     "legendFormat": "Transmit {{device}} "
    }
   ]
  },
  {
   "title": "Network RX / TX: Top 10",
   "type": "timeseries",
   "description": "Top 10 chattering nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (instance) (rate(node_network_receive_bytes_total[5m])) + sum by (instance) (irate(node_network_transmit_bytes_total[5m])) * 8)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target Latency by Operation",
     "type": "timeseries",
     "description": "AIStore target request latencies.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum({__name__=~\"ais_target_${target}_get_ms\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum({__name__=~\"ais_target_${target}_get_redir_ms\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum({__name__=~\"ais_target_${target}_put_ms\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum({__name__=~\"ais_target_${target}_put_redir_ms\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum({__name__=~\"ais_target_${target}_keepalive_ms\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum({__name__=~\"ais_target_${target}_list_ms\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}