{
 "title": "AIStore Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "metricsSource", "label": "Metrics Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(ais_proxy_uptime,cluster)"
    }
   },
   {
    "name": "proxy",
    "label": "Proxy",
    "query": {
     "query": "label_values(ais_proxy_uptime{cluster=\"$cluster\"},node_id)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(ais_target_uptime{cluster=\"$cluster\"},node_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(ais_proxy_uptime{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_statefulset_replicas{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "NIC",
    "label": "NICs",
    "query": {
     "query": "label_values(node_network_info{cluster=\"$cluster\"},device)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m, 5m, 10m, 30m, 1h, 6h, 12h, 24h"
   }
  ]
 },
 "panels": [
  { "title": "AIStore Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used Capacity",
   "type": "gauge",
   "description": "Percentage of AIStore storage used across the cluster",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-sum(node_filesystem_avail_bytes{instance=~\"^${node}$\", job=\"node-exporter\", mountpoint=~\"/ais/.*\", fstype!=\"rootfs\", cluster=~\"${cluster}\"})/ sum(node_filesystem_size_bytes{instance=~\"^${node}$\", job=\"node-exporter\", mountpoint=~\"/ais/.*\", fstype!=\"rootfs\", cluster=~\"${cluster}\"})) \n* 100"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "description": "Total Raw Storage Capacity",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}\",mountpoint=~\"/ais/.+\",cluster=~\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "The number of GET errors across the selected targets within the specified time interval",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$target_get_err + $target_put_err",
     "type": "math"
    }
   ]
  },
  {
   "title": "GET Throughput",
   "type": "stat",
   "description": "Current AIStore GET Throughput",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable K8s Nodes",
   "type": "stat",
   "description": "Unavailable cluster nodes",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\", condition=\"Ready\", status!=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Gateways",
   "type": "stat",
   "description": "Count of total unavailable proxies in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$total_replicas-$ready_replicas",
     "type": "math"
    }
   ]
  },
  {
   "title": "Unavailable Targets",
   "type": "stat",
   "description": "Total unavailable targets count",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$total_replicas - $ready_replicas",
     "type": "math"
    }
   ]
  },
  {
   "title": "Requests / Sec",
   "type": "stat",
   "description": "Total AIStore requests per second",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$put_requests + $get_requests", "type": "math" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Mean target request latency for GET requests over the selected interval",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$ns_over_interval / $request_over_interval",
     "type": "math"
    }
   ]
  },
  {
   "title": "PUT Throughput",
   "type": "stat",
   "description": "Current AIStore PUT Throughput",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total K8s Nodes",
   "type": "stat",
   "description": "Count of physical machines in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=~\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Total Gateways",
   "type": "stat",
   "description": "Count of total proxies in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*proxy\", namespace=\"${namespace}\", cluster=~\"${cluster}\"}"
    }
   ]
  },
  {
   "title": "Total Targets",
   "type": "stat",
   "description": "AIStore target replica count",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*target\", namespace=\"${namespace}\", cluster=~\"${cluster}\"}"
    }
   ]
  },
  { "title": "Hardware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Mean busy state of all CPU cores",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum(irate(node_cpu_seconds_total{instance=~\"$node\", mode!=\"idle\", cluster=~\"${cluster}\"}[$interval]))\n  / \n  sum(irate(node_cpu_seconds_total{instance=~\"$node\", cluster=~\"${cluster}\"}[$interval]))\n  * 100\n)"
    }
   ]
  },
  {
   "title": "Load (5m)",
   "type": "gauge",
   "description": "Mean 5m load average",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"^${node}$\", cluster=~\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Mean RAM usage",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes{instance=~\"^${node}$\",job=\"node-exporter\", cluster=~\"${cluster}\"} / node_memory_MemTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\", cluster=~\"${cluster}\"})) * 100)"
    }
   ]
  },
  {
   "title": "Core Count",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"^${node}$\",job=\"node-exporter\", cluster=~\"${cluster}\"}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Identifies the pod within the AIS namespace that has the lowest uptime",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(ais_target_uptime{job=\"aistore\", cluster=~\"${cluster}\"})\n"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"^${node}\",job=\"node-exporter\", cluster=~\"${cluster}\"})"
    }
   ]
  },
  { "title": "Target Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total GET Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Throughput by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Throughput by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GET Object Size by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (\n  rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])\n)\n/\nsum by (bucket) (\n  rate(ais_target_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average PUT Object Size by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$throughput/$count", "type": "math" }
   ]
  },
  {
   "title": "GET Throughput per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Throughput per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(node_id) (ais_target_disk_read_bps{node_id=~\"$target\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(node_id) (ais_target_disk_write_bps{node_id=~\"$target\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(ais_target_disk_util{node_id=~\"$target\", cluster=\"$cluster\"}) by (node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Read and Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(ais_target_disk_read_bps{cluster=~\"${cluster}\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(ais_target_disk_write_bps{cluster=~\"${cluster}\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "GET Latency per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(ais_target_get_ns_total{cluster=\"$cluster\"}[$interval])) / sum by (bucket) (rate(ais_target_get_count{cluster=\"$cluster\"}[$interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Latency per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expression": "$latency_total/$count", "type": "math" }
   ]
  },
  {
   "title": "Total GET Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cold GET Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_remote_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cold GET Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_remote_get_bytes_total{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_put_count{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "GET Requests/sec per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_proxy_get_count{node_id=~\"$proxy\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, mountpoint) (\n    node_filesystem_size_bytes{instance=~\"^${node}$\", mountpoint=~\"/ais/.+\", cluster=~\"${cluster}\"} - \n    node_filesystem_avail_bytes{instance=~\"^${node}$\", mountpoint=~\"/ais/.+\", cluster=~\"${cluster}\"}\n)",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Storage Used vs Free",
   "type": "timeseries",
   "description": "Total cluster storage used and free",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{cluster=\"$cluster\",mountpoint=~\"^/ais/.+\"})",
     "legendFormat": "Free Storage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\",mountpoint=~\"^/ais/.+\"}) - sum(node_filesystem_avail_bytes{cluster=\"$cluster\",mountpoint=~\"^/ais/.+\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Storage Used: Top 5 Disks",
   "type": "timeseries",
   "description": "Top five storage-using disks and nodes, as % full",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, (1 - (sum by (instance, device) (node_filesystem_avail_bytes{cluster=~\"${cluster}\",instance=~\"^${node}$\",mountpoint=~\"^/ais/.*\"}) / sum by (instance, device) (node_filesystem_size_bytes{cluster=~\"${cluster}\",instance=~\"^${node}$\",mountpoint=~\"^/ais/.*\"}))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Error Rates By Node",
   "type": "timeseries",
   "description": "Disk error rates, broken down by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_filesystem_device_error{cluster=~\"${cluster}\",instance=~\"${node}\", mountpoint=~\"^/ais/.*$\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "AIS Target Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "sum(increase(ais_target_err_http_write_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "HTTP Write"
    },
    {
     "expr": "sum(increase(ais_target_err_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(increase(ais_target_err_dl_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(increase(ais_target_err_kalive_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "Keepalive"
    },
    {
     "expr": "sum(increase(ais_target_err_lcache_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "Lcache"
    },
    {
     "expr": "sum(increase(ais_target_err_io_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "IO GET"
    }
   ]
  },
  {
   "title": "AIS Proxy Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "sum(increase(ais_proxy_err_http_write_count{node_id=~\"$proxy\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "HTTP Write"
    },
    {
     "expr": "sum(increase(ais_proxy_err_kalive_count{node_id=~\"$proxy\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "Keepalive"
    },
    {
     "expr": "sum(increase(ais_proxy_err_lst_count{node_id=~\"$proxy\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "List"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Network RX / TX: Top 5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (instance) (irate(node_network_receive_bytes_total{cluster=~\"${cluster}\",instance=~\"$node\",device=~\"$NIC\"}[$interval])))",
     "legendFormat": "{{instance}}-rx"
    },
    {
     "expr": "topk(5, sum by (instance) (irate(node_network_transmit_bytes_total{cluster=~\"${cluster}\",instance=~\"$node\",device=~\"$NIC\"}[$interval])))",
     "legendFormat": "{{instance}}-tx"
    }
   ]
  }
 ]
}