{
 "title": "AIStore Dashboard -- Legacy (<v3.26)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(ais_proxy_uptime,cluster)"
    }
   },
   {
    "name": "proxy",
    "label": "Proxy",
    "query": {
     "query": "label_values(ais_proxy_get_count{cluster=\"$cluster\"},node_id)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(ais_target_get_count{cluster=\"$cluster\"},node_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(ais_proxy_uptime{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(node_namespace_pod:kube_pod_info:{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "node_count",
    "query": {
     "query": "query_result(count(kube_node_info{cluster=\"$cluster\"}))"
    }
   },
   { "name": "NIC", "label": "NICs", "query": { "query": "label_values(device)" } },
   {
    "name": "interval",
    "label": "interval",
    "query": "30s, 1m, 5m, 10m, 30m, 1h, 6h, 12h, 24h"
   }
  ]
 },
 "panels": [
  { "title": "AIStore Dashboard -- Legacy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used Capacity",
   "type": "gauge",
   "description": "Percentage of AIStore storage used across the cluster",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-sum(node_filesystem_avail_bytes{instance=~\"^${node}$\", job=\"node-exporter\", mountpoint=~\"/ais/.*\", fstype!=\"rootfs\", cluster=~\"${cluster}\"})/ sum(node_filesystem_size_bytes{instance=~\"^${node}$\", job=\"node-exporter\", mountpoint=~\"/ais/.*\", fstype!=\"rootfs\", cluster=~\"${cluster}\"})) \n* 100"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "description": "Total Raw Storage Capacity",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\", cluster=~\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "The per-second rate of GET errors across the selected targets within the specified time interval",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ais_target_err_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) \n+ \nsum(increase(ais_target_err_put_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) or on() vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Throughput",
   "type": "stat",
   "description": "Current AIStore GET Throughput",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) / (1024 * 1024) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable K8s Nodes",
   "type": "stat",
   "description": "Unavailable cluster nodes",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{daemonset=\"kube-prometheus-stack-prometheus-node-exporter\", cluster=~\"${cluster}\"}\n"
    }
   ]
  },
  {
   "title": "Unavailable Gateways",
   "type": "stat",
   "description": "Count of total unavailable proxies in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=~\".*proxy$\", namespace=\"${namespace}\", cluster=~\"${cluster}\"}) - min(kube_statefulset_status_replicas_ready{statefulset=~\".*proxy$\", namespace=\"${namespace}\", cluster=~\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Unavailable Targets",
   "type": "stat",
   "description": "Total unavailable targets count",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=~\".*target$\", namespace=\"${namespace}\", cluster=~\"${cluster}\"}) - min(kube_statefulset_status_replicas_ready{statefulset=~\".*target$\", namespace=\"${namespace}\", cluster=~\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Requests / Sec",
   "type": "stat",
   "description": "Total AIStore requests per second",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Mean AIstore target request latency for operations.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ais_target_get_ms{node_id=~\"$target\", cluster=~\"$cluster\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Throughput",
   "type": "stat",
   "description": "Current AIStore PUT Throughput",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) / (1024 * 1024) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total K8s Nodes",
   "type": "stat",
   "description": "Count of physical machines in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=~\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Total Gateways",
   "type": "stat",
   "description": "Count of total proxies in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*proxy\", namespace=\"${namespace}\", cluster=~\"${cluster}\"}"
    }
   ]
  },
  {
   "title": "Total Targets",
   "type": "stat",
   "description": "AIStore target replica count",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*target\", namespace=\"${namespace}\", cluster=~\"${cluster}\"}"
    }
   ]
  },
  { "title": "Hardware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Mean busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"^$node$\",job=\"node-exporter\", mode!=\"idle\", cluster=~\"${cluster}\"}[$interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"^${node}$\",job=\"node-exporter\", cluster=~\"${cluster}\"}[$interval])))) * 100)\n"
    }
   ]
  },
  {
   "title": "Load (5m)",
   "type": "gauge",
   "description": "Mean 5m load average",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load5{instance=~\"^${node}$\",job=\"node-exporter\", cluster=~\"${cluster}\"}) / count(count(node_cpu_seconds_total{instance=~\"^${node}$\", job=\"node-exporter\", cluster=~\"${cluster}\"}) by (cpu, instance))) * 100"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Mean RAM usage",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{instance=~\"^${node}$\",job=\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\"}))"
    }
   ]
  },
  {
   "title": "Core Count",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"^${node}$\",job=\"node-exporter\", cluster=~\"${cluster}\"}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Identifies the pod within the AIS namespace that has the lowest uptime",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(ais_target_uptime{container=\"ais-node\", namespace=\"${namespace}\", cluster=~\"${cluster}\"})\n"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"^${node}\",job=\"node-exporter\", cluster=~\"${cluster}\"})"
    }
   ]
  },
  { "title": "Target Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total GET Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) / (1024 * 1024) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) / (1024 * 1024) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean GET Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])/rate(ais_target_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean PUT Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])/rate(ais_target_put_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Throughput per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval])) / (1024 * 1024) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Throughput per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by (node_id) (ais_target_put_mbps{node_id=~\"$target\", cluster=~\"${cluster}\"})/1.048576 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by (node_id) (sum by (node_id) (ais_target_disk_read_mbps{node_id=~\"$target\", cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by (node_id) (sum by (node_id) (ais_target_disk_write_mbps{node_id=~\"$target\", cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(ais_target_disk_util{node_id=~\"$target\", cluster=~\"${cluster}\"}) by (node_id) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Read and Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(ais_target_disk_read_mbps{cluster=~\"${cluster}\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(ais_target_disk_write_mbps{cluster=~\"${cluster}\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "GET Latency per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (node_id) (ais_target_get_ms{node_id=~\"$target\", cluster=~\"${cluster}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Latency per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (node_id) (ais_target_put_ms{node_id=~\"$target\", cluster=~\"${cluster}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cold GET Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_remote_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cold GET Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_remote_get_bytes_total{node_id=~\"$target\", cluster=~\"${cluster}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_put_count{node_id=~\"$target\", cluster=~\"${cluster}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_put_bytes{node_id=~\"$target\", cluster=~\"${cluster}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "GET Requests/sec per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_proxy_get_count{node_id=~\"$proxy\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_disk_io_time_seconds_total{instance=~\"$node\", device=~\"nvme.*\", cluster=~\"${cluster}\"}[$interval]))\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    node_filesystem_size_bytes{instance=~\"$node\", job=\"node-exporter\", device!~\"rootfs\"} - \n    node_filesystem_avail_bytes{instance=~\"$node\", job=\"node-exporter\", device!~\"rootfs\"}\n)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Storage Used vs Free",
   "type": "timeseries",
   "description": "Total cluster storage used and free",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"})",
     "legendFormat": "Free Storage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Storage Used: Top 5 Disks",
   "type": "timeseries",
   "description": "Top five storage-using disks and nodes, as % full",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, (100 - 100 * sum by (instance, device) (node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"}) / sum by (instance, device) (node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"})))\n",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "AIStore Error Rates by Operation",
   "type": "timeseries",
   "description": "AIStore error rates, broken down by operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(increase(ais_target_err_put_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(increase(ais_target_err_get_count{node_id=~\"$target\", cluster=~\"${cluster}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Error Rates By Node",
   "type": "timeseries",
   "description": "Disk error rates, broken down by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_filesystem_device_error{mountpoint=~\"^/ais/.*$\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Total Network RX / TX",
   "type": "timeseries",
   "description": "Total receive and transmit cluster network throughput",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"$NIC\"}[5m]))",
     "legendFormat": "Recieve {{device}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"$NIC\"}[5m]))",
     "legendFormat": "Transmit {{device}} "
    }
   ]
  },
  {
   "title": "Network RX / TX: Top 10",
   "type": "timeseries",
   "description": "Top 10 chattering nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (instance) (rate(node_network_receive_bytes_total{device=~\"$NIC\"}[$interval])) + sum by (instance) (irate(node_network_transmit_bytes_total{device=~\"$NIC\"}[$interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}