releases:
  - name: aisloader-graphite
    namespace: "{{ .Values | get \"namespace\" \"ais\" }}"
    createNamespace: true
    chart: ./charts/graphite

  - name: aisloader
    namespace: "{{ .Values | get \"namespace\" \"ais\" }}"
    createNamespace: true
    chart: ./charts/benchmark
