---
name: "🐞 Bug Report"
description: Report a bug
title: "(short issue description)"
labels: [bug, needs-triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened?
        
        Please include full errors, uncaught exceptions, stack traces, and relevant logs. 
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps To Reproduce
      description: |
        Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
        Avoid including business logic or unrelated code, it makes diagnosis more difficult.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: |
        Anything else that might be relevant for troubleshooting this bug. Providing context helps us come up with a solution that is most useful in the real world.
    validations:
      required: false
  - type: input
    id: operator-version
    attributes:
      label: AIS Operator version
      description: |
        If this is a bug with the AIS Operator, please specify the operator version you are using. For example, `latest`, `v2.3.0`, etc.
    validations:
      required: false
  - type: input
    id: ais-version
    attributes:
      label: AIStore version
      description: |
        If this is a bug with the AIS Operator, please specify the AIS version you are using. For example, `latest`, `v3.29`, etc.
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment details (K8s deployment type and version, etc.)
    validations:
      required: true