{
 "title": "AIStore Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "proxy",
    "label": "Proxy",
    "query": {
     "query": "label_values(ais_proxy_get_n,node_id)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(ais_target_get_n,node_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance) "
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(node_namespace_pod:kube_pod_info:,namespace)"
    }
   },
   {
    "name": "node_count",
    "query": {
     "query": "query_result(count(kube_node_info))"
    }
   },
   { "name": "NIC", "label": "NIC", "query": { "query": "label_values(device)" } }
  ]
 },
 "panels": [
  { "title": "AIStore Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GET Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_n{node_id=~\"$target\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_size{node_id=~\"$target\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "description": "Percentage of AIStore storage used across the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})) / sum(node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "stat",
   "description": "Total Raw Storage Capacity",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})\n"
    }
   ]
  },
  {
   "title": "Unavailable Nodes",
   "type": "stat",
   "description": "Unavailable cluster nodes",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{daemonset=\"kube-prometheus-stack-prometheus-node-exporter\"}\n"
    }
   ]
  },
  {
   "title": "Unavailable Proxies",
   "type": "stat",
   "description": "Count of total unavailable proxies in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=~\".*proxy$\", namespace=\"${namespace}\"}) - min(kube_statefulset_status_replicas_ready{statefulset=~\".*proxy$\", namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Unavailable Targets",
   "type": "stat",
   "description": "Total unavailable targets count",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=~\".*target$\", namespace=\"${namespace}\"}) - min(kube_statefulset_status_replicas_ready{statefulset=~\".*target$\", namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Total Cold GET Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_cold_n{node_id=~\"$target\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cold GET Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_get_cold_size{node_id=~\"$target\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total AIstore errors / sec",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_err_get_n{node_id=~\"$target\"}[5m])) or on() vector(0)\n",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Requests / Sec",
   "type": "stat",
   "description": "Total AIStore requests per second",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_n[5m])) or vector(0)\n",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "Count of physical machines in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Proxy Count",
   "type": "stat",
   "description": "Count of total proxies in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*proxy\", namespace=\"${namespace}\"}"
    }
   ]
  },
  {
   "title": "Target Count",
   "type": "stat",
   "description": "AIStore target replica count",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=~\".*target\", namespace=\"${namespace}\"}"
    }
   ]
  },
  {
   "title": "Total PUT Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_put_n{node_id=~\"$target\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ais_target_put_size{node_id=~\"$target\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Mean AIstore target request latency for operations.",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_ms{node_id=~\"$target\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_get_redir_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_put_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_put_redir_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_keepalive_ms\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({__name__=~\"ais_target_${target}_list_ms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Total receive and transmit cluster network throughput",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{device=\"$NIC\"}[5m])) + sum(rate(node_network_transmit_bytes_total{device=\"$NIC\"}[5m])))",
     "legendFormat": "Recieve {{device}}"
    }
   ]
  },
  { "title": "Hardware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Mean busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum by(instance) (irate(node_cpu_seconds_total{instance=~\"^$node$\",job=\"node-exporter\", mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"^${node}$\",job=\"node-exporter\"}[5m])))) * 100)\n"
    }
   ]
  },
  {
   "title": "Load (5m)",
   "type": "gauge",
   "description": "Mean 5m load average",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load5{instance=~\"^${node}$\",job=\"node-exporter\"}) / count(count(node_cpu_seconds_total{instance=~\"^${node}$\", job=\"node-exporter\"}) by (cpu, instance))) * 100"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Mean RAM usage",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{instance=~\"^${node}$\",job=\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\"}))"
    }
   ]
  },
  {
   "title": "Max Root FS",
   "type": "gauge",
   "description": "The top root filesystem usage across the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(100 - ((node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/\",fstype!=\"rootfs\"}))\n"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "description": "Mean swap usage",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((node_memory_SwapTotal_bytes{instance=~\"^${node}$$\",job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~\"^${node}$\",job=\"node-exporter\"}) / (node_memory_SwapTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\"} )) * 100)"
    }
   ]
  },
  {
   "title": "Core Count",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"^${node}$\",job=\"node-exporter\"}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"^${node}\",job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"^${node}$\",job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    node_time_seconds{instance=~\"$node\"} - node_boot_time_seconds{instance=~\"$node\"}\n)\n"
    }
   ]
  },
  { "title": "Target Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total GET Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_get_size{node_id=~\"$target\"}[1m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total PUT Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(ais_target_put_size{node_id=~\"$target\"}[1m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. GET Object Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "avg(rate(ais_target_get_size{node_id=~\"$target\"}[5m])/rate(ais_target_get_n{node_id=~\"$target\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. PUT Object Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "avg(rate(ais_target_put_size{node_id=~\"$target\"}[5m])/rate(ais_target_put_n{node_id=~\"$target\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Throughput per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by (node_id) (ais_target_get_mbps{node_id=~\"$target\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Throughput per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by (node_id) (ais_target_put_mbps{node_id=~\"$target\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Kibits" } },
   "targets": [
    {
     "expr": "avg(rate(ais_target_disk_read_mbps{node_id=~\"$target\"}[2m])) by (node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg(rate(ais_target_disk_write_mbps{node_id=~\"$target\"}[2m])) by (node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(ais_target_disk_util{node_id=~\"$target\"}[2m])) by (node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Read and Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "sum(ais_target_disk_read_mbps)", "legendFormat": "Read" },
    {
     "expr": "sum({__name__=~\"ais_target_disk_write_mbps\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "GET Latency per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_target_get_ms{node_id=~\"$target\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT Latency per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_target_put_ms{node_id=~\"$target\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "GET Requests/sec per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (node_id) (rate(ais_proxy_get_n{node_id=~\"$proxy\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_disk_io_time_seconds_total{instance=~\"$node\", device=~\"nvme.*\"}[5m]))\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    node_filesystem_size_bytes{instance=~\"$node\", job=\"node-exporter\", device!~\"rootfs\"} - \n    node_filesystem_avail_bytes{instance=~\"$node\", job=\"node-exporter\", device!~\"rootfs\"}\n)\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Storage Used vs Free",
   "type": "timeseries",
   "description": "Total cluster storage used and free",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"})",
     "legendFormat": "Free Storage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"}) - sum(node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"/ais/.*\",fstype!=\"rootfs\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Storage Used: Top 5 Disks",
   "type": "timeseries",
   "description": "Top five storage-using disks and nodes, as % full",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, (100 - 100 * sum by (instance, device) (node_filesystem_avail_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"}) / sum by (instance, device) (node_filesystem_size_bytes{instance=~\"^${node}$\",job=\"node-exporter\",mountpoint=~\"^/ais/.*\",fstype!=\"rootfs\"})))\n",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "AIStore Error Rates by Operation",
   "type": "timeseries",
   "description": "AIStore error rates, broken down by operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "sum(increase(ais_target_err_get_n[5m])) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_get_n\"}[5m]))",
     "legendFormat": "Total errors / sec"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_delete_n\"}[5m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_post_n\"}[5m]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_put_n\"}[5m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_head_n\"}[5m]))",
     "legendFormat": "HEAD"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_list_n\"}[5m]))",
     "legendFormat": "list"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_range_n\"}[5m]))",
     "legendFormat": "range"
    },
    {
     "expr": "sum(rate({__name__=~\"ais_proxy_${proxy}_err_dl_n\"}[5m]))",
     "legendFormat": "dl"
    }
   ]
  },
  {
   "title": "Disk Error Rates By Node",
   "type": "timeseries",
   "description": "Disk error rates, broken down by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_filesystem_device_error{mountpoint=~\"^/ais/.*$\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Total Network RX / TX",
   "type": "timeseries",
   "description": "Total receive and transmit cluster network throughput",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"$NIC\"}[5m]))",
     "legendFormat": "Recieve {{device}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=\"$NIC\"}[5m]))",
     "legendFormat": "Transmit {{device}} "
    }
   ]
  },
  {
   "title": "Network RX / TX: Top 10",
   "type": "timeseries",
   "description": "Top 10 chattering nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (instance) (rate(node_network_receive_bytes_total{device=\"$NIC\"}[5m])) + sum by (instance) (irate(node_network_transmit_bytes_total{device=\"$NIC\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}