environments:
  default:
    values:
      - valuesPath: "./config/authn/default.yaml.gotmpl"
        cert:
          valuesPath: "./config/authn/cert/default.yaml"
  local:
    values:
      - valuesPath: "./config/authn/local.yaml.gotmpl"
        cert:
          valuesPath: "./config/authn/cert/local.yaml"

  tls:
    values:
      - valuesPath: "./config/authn/tls.yaml.gotmpl"
        cert:
          valuesPath: "./config/authn/cert/tls.yaml"
  oci-ord:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/oci-ord.yaml.gotmpl?ref=main"
        cert:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/oci-ord.yaml?ref=main"
  oci-iad:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/oci-iad.yaml.gotmpl?ref=main"
        cert:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/oci-iad.yaml?ref=main"
  sjc4-dev:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/nvidia.yaml.gotmpl?ref=main"
        cert:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/sjc4-dev.yaml?ref=main"
  sjc112:
    values:
      - valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/nvidia.yaml.gotmpl?ref=main"
        cert:
          valuesPath: "git::ssh://git@gitlab-master.nvidia.com/aistorage/ais-infra.git@helm/authn/config/authn/cert/sjc112.yaml?ref=main"
---
hooks:
  - events: ["prepare"]
    showlogs: true
    command: helmfile
    args: ["cache", "cleanup"]
  - events: ["prepare"]
    showlogs: true
    command: bash
    args: ["../confirm.sh", "{{ .Environment.Name }}"]

releases:
  - name: ais-authn
    namespace: ais
    createNamespace: true
    chart: charts/authn
    version: 0.5.0
    values:
      - "./charts/authn/values.yaml.gotmpl"
      - "{{ .Environment.Values.valuesPath }}"
      - "{{ .Environment.Values.cert.valuesPath }}"
