apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ais-operator.fullname" . }}-subject-token-role
  labels:
  {{- include "ais-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ais-operator.fullname" . }}-subject-token-rolebinding
  labels:
  {{- include "ais-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "ais-operator.fullname" . }}-subject-token-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "ais-operator.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
