#!/usr/bin/env bash
#
# Sysctl config tuner — generates the sysctl section for AIS config.yaml
# based on host capabilities provided by the user along with some AIS defaults
#
# Usage: bash sysctl-tuner.sh
#   Prompts for inputs, then prints YAML for the "sysctl:" section to stdout.
#   Redirect to a file or paste into config.yaml.
#
# tcp_mem formula (RHEL 8+): limit = nr_free_buffer_pages / divisor;
#   min = limit*3/4, pressure = limit, max = min*2.
# See: https://access.redhat.com/solutions/6964027
#
set -euo pipefail

# --- helpers (portable arithmetic with awk) ---
_awk_calc() { awk "BEGIN { printf \"%.0f\", $* }"; }
_awk_int()  { awk "BEGIN { print int($*) }"; }

# Round up to next power of 2 (for buffer sizes)
_next_pow2() {
    local v="$1"
    awk -v v="$v" 'BEGIN {
        if (v <= 0) { print 65536; exit }
        n = 1; while (n < v) n *= 2
        print n
    }'
}

prompt_val() {
    local name="$1" default="$2" unit="${3:-}"
    local prompt="[$name] ($unit)"
    [[ -n "$default" ]] && prompt="$prompt [default: $default]"
    read -r -p "$prompt: " val
    if [[ -z "$val" ]]; then
        echo "$default"
    else
        echo "$val"
    fi
}

echo "AIS sysctl config tuner — generates sysctl section for config.yaml"
echo ""

MEM_GB=$(prompt_val "Memory" "512" "GiB")
Gbps=$(prompt_val "Network throughput" "100" "Gbps")
DIVISOR=$(prompt_val "tcp_mem pressure divisor (RHEL default 16)" "16" "")
RTT_MS=$(prompt_val "RTT for BDP" "5" "ms")
VM_MIN_FREE_PCT=$(prompt_val "vm.min_free_kbytes as % of RAM" "1" "%")

# derived values (memory in GiB: 1024³ bytes)
# tcp_mem: approximate nr_free_buffer_pages as (mem_GiB * 1024 * 1024 / 4) pages
PAGES=$(_awk_calc "$MEM_GB * 1024 * 1024 / 4")
LIMIT=$(_awk_int "$PAGES / $DIVISOR")
[[ "$LIMIT" -lt 128 ]] && LIMIT=128
TCP_MEM_MIN=$(_awk_int "$LIMIT * 3 / 4")
TCP_MEM_PRESSURE=$LIMIT
TCP_MEM_MAX=$(_awk_int "$TCP_MEM_MIN * 2")

# BDP = bandwidth * RTT; buffer max = 2*BDP, rounded up to next power of 2
# BDP_bytes = (Gbps * 1e9/8) * (RTT_MS/1000)
BDP_BYTES=$(_awk_calc "($Gbps * 1e9/8) * ($RTT_MS/1000)")
BUF_TARGET=$(_awk_int "2 * $BDP_BYTES")
BUF_MAX=$(_next_pow2 "$BUF_TARGET")
# Clamp to at least 64KB, at most 512MB
[[ "$BUF_MAX" -lt 65536 ]] && BUF_MAX=65536
[[ "$BUF_MAX" -gt 536870912 ]] && BUF_MAX=536870912

# optmem_max: ~24 MB or 1/4 of buffer max, whichever is larger (capped ~64MB)
OPTMEM=$(_awk_int "$BUF_MAX / 4")
[[ "$OPTMEM" -lt 25165824 ]] && OPTMEM=25165824
[[ "$OPTMEM" -gt 67108864 ]] && OPTMEM=67108864

# vm.min_free_kbytes: configurable % of RAM
VM_MIN_FREE_KB=$(_awk_int "$MEM_GB * 1024 * 1024 * $VM_MIN_FREE_PCT / 100")
[[ "$VM_MIN_FREE_KB" -lt 65536 ]] && VM_MIN_FREE_KB=65536

# emit YAML readable by ais_host_config.sh
echo ""
echo "# Generated by sysctl-tuner.sh -- memory ${MEM_GB} GiB, ${Gbps} Gbps, tcp_mem divisor ${DIVISOR}, RTT ${RTT_MS} ms, vm.min_free_kbytes ${VM_MIN_FREE_PCT}%"
echo "# BDP ~= $(_awk_int "$BDP_BYTES / 1024 / 1024") MB -- buffer max ${BUF_MAX} bytes"
echo "sysctl:"
echo "  required:"
echo "    net.core.somaxconn: 65535"
echo "    net.ipv4.tcp_tw_reuse: 1"
echo "    net.ipv4.ip_local_port_range: \"2048 65535\""
echo "    net.ipv4.tcp_max_tw_buckets: 1440000"
echo ""
echo "  # Network buffer sizes -- BDP-based (throughput ${Gbps} Gbps, RTT ${RTT_MS} ms)."
echo "  net:"
echo "    net.ipv4.ip_forward: 1"
echo "    net.core.optmem_max: $OPTMEM"
echo "    net.core.rmem_max: $BUF_MAX"
echo "    net.core.wmem_max: $BUF_MAX"
echo "    net.core.netdev_max_backlog: 250000"
echo "    net.ipv4.tcp_mem: \"$TCP_MEM_MIN $TCP_MEM_PRESSURE $TCP_MEM_MAX\""
echo "    net.ipv4.tcp_wmem: \"4096 16384 $BUF_MAX\""
echo "    net.ipv4.tcp_rmem: \"4096 262144 $BUF_MAX\""
echo "    net.ipv4.tcp_adv_win_scale: 1"
echo "    net.ipv4.tcp_mtu_probing: 2"
echo "    net.ipv4.tcp_slow_start_after_idle: 0"
echo "    net.ipv4.tcp_max_syn_backlog: 100000"
echo "    net.ipv4.tcp_rfc1337: 1"
echo "    net.netfilter.nf_conntrack_tcp_be_liberal: 1"
echo ""
echo "  # VM tuning -- min_free_kbytes ${VM_MIN_FREE_PCT}% of ${MEM_GB} GiB RAM."
echo "  vm:"
echo "    vm.swappiness: 10"
echo "    vm.min_free_kbytes: $VM_MIN_FREE_KB"
echo "    vm.vfs_cache_pressure: 50"
