{{- if and .Values.tls.enabled .Values.tls.createCert }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.secretName }}
  isCA: false
  duration: {{ .Values.tls.certificate.duration }}
  renewBefore: {{ .Values.tls.certificate.renewBefore }}
  usages:
    - server auth
  {{- with .Values.tls.certificate.subject }}
  subject:
    {{- with .organizations }}
    organizations:
      {{- range . }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- with .organizationalUnits }}
    organizationalUnits:
      {{- range . }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- with .countries }}
    countries:
      {{- range . }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  dnsNames:
    - localhost
    {{- range .Values.tls.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
  ipAddresses:
    - 127.0.0.1
    {{- range .Values.tls.certificate.ipAddresses }}
    - {{ . }}
    {{- end }}
  {{- with .Values.tls.certificate.emailAddresses }}
  emailAddresses:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  issuerRef:
    name: {{ .Values.tls.certificate.issuerRef.name }}
    kind: {{ .Values.tls.certificate.issuerRef.kind }}
{{- end }}
