{{- if eq .Values.signing.method "hmac" }}
---
# K8s Secret with the HMAC JWT signing key
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-signing-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
type: Opaque
stringData:
  SIGNING-KEY: {{ .Values.signing.key | quote }}
{{- end }}
{{- if and (eq .Values.signing.method "rsa") .Values.signing.privateKeyPass }}
---
# K8s Secret with the RSA private key passphrase
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rsa-passphrase
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
type: Opaque
stringData:
  RSA-PASSPHRASE: {{ .Values.signing.privateKeyPass | quote }}
{{- end }}
---
# K8s Secret with the superuser credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-su-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
type: Opaque
stringData:
  SU-NAME: {{ .Values.superuser.name | quote }}
  SU-PASS: {{ .Values.superuser.password | quote }}
---
# ConfigMap for AuthN Server with the default configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
data:
  authn.json: |
    {
      "log": {
        "dir": "{{ .Values.log.dir }}",
        "level": "{{ .Values.log.level }}",
        "flush_interval": "{{ .Values.log.flushInterval }}"
      },
      "net": {
        {{- if .Values.net.externalURL }}
        "external_url": "{{ .Values.net.externalURL }}",
        {{- end }}
        "http": {
          "port": {{ .Values.applicationPort }},
          "use_https": {{ .Values.tls.enabled }},
          "server_crt": "{{ if .Values.tls.enabled }}{{ .Values.tls.certPath }}{{ end }}",
          "server_key": "{{ if .Values.tls.enabled }}{{ .Values.tls.keyPath }}{{ end }}"
        }
      },
      "auth": {
        "expiration_time": "{{ .Values.auth.expirationTime }}",
        "rsa_key_bits": {{ .Values.signing.rsaKeyBits }}
        {{- if .Values.db.type }},
        "db": {
          "type": "{{ .Values.db.type }}"
          {{- if .Values.db.filepath }},
          "filepath": "{{ .Values.db.filepath }}"
          {{- end }}
        }
        {{- end }}
      },
      "timeout": {
        "default_timeout": "{{ .Values.timeout.defaultTimeout }}"
      }
    }
{{- if .Values.persistence.enabled }}
{{- if and (not .Values.persistence.storageClass) (not .Values.persistence.pvName) }}
---
# AuthN PV for storing AuthN configuration and user data (hostPath)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    {{- include "authn.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.hostPath }}
  persistentVolumeReclaimPolicy: Retain
{{- end }}
---
# AuthN PVC for storing AuthN configuration and user data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- else if .Values.persistence.pvName }}
  volumeName: {{ .Values.persistence.pvName }}
  {{- end }}
{{- end }}
