name: Build -- Operator

on:
  pull_request:
    paths:
      - 'operator/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: operator
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: operator/go.mod
          cache-dependency-path: operator/go.sum

      - name: Build
        run: make build