{{- $kind := .Values.issuerKind | default "ClusterIssuer" }}
{{- if not (or (eq $kind "ClusterIssuer") (eq $kind "Issuer")) }}
{{- fail "issuerKind must be either 'ClusterIssuer' or 'Issuer'" }}
{{- end }}
{{- $defaultNamespace := ternary "cert-manager" .Release.Namespace (eq $kind "ClusterIssuer") }}
{{- $namespace := .Values.namespace | default $defaultNamespace }}
---
apiVersion: cert-manager.io/v1
kind: {{ $kind }}
metadata:
  name: {{ .Values.selfSignedIssuer.name }}
  {{- if eq $kind "Issuer" }}
  namespace: {{ $namespace }}
  {{- end }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.caCertificate.name }}
  namespace: {{ $namespace }}
spec:
  isCA: true
  commonName: {{ .Values.caCertificate.commonName }}
  secretName: {{ .Values.caCertificate.secretName }}
  duration: {{ .Values.caCertificate.duration }}
  renewBefore: {{ .Values.caCertificate.renewBefore }}
  privateKey:
    algorithm: {{ .Values.caCertificate.privateKey.algorithm }}
    encoding: {{ .Values.caCertificate.privateKey.encoding }}
    size: {{ .Values.caCertificate.privateKey.size }}
  {{- if .Values.caCertificate.subject }}
  {{- if or .Values.caCertificate.subject.organizations .Values.caCertificate.subject.organizationalUnits .Values.caCertificate.subject.countries }}
  subject:
    {{- with .Values.caCertificate.subject.organizations }}
    organizations: {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.caCertificate.subject.organizationalUnits }}
    organizationalUnits: {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.caCertificate.subject.countries }}
    countries: {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
  issuerRef:
    name: {{ .Values.selfSignedIssuer.name }}
    kind: {{ $kind }}
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: {{ $kind }}
metadata:
  name: {{ .Values.caIssuer.name }}
  {{- if eq $kind "Issuer" }}
  namespace: {{ $namespace }}
  {{- end }}
spec:
  ca:
    secretName: {{ .Values.caCertificate.secretName }}
